version: "2"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=app
       - MYSQL_USER=app
       - MYSQL_PASSWORD=app
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports :
      - "8081:80"
     links:
      - mysql:db